<h1>Assignment 1: <strong> Foundations & Tensor Operations</strong></h1>
Name : Sammit Poudyal <br/>
Class: CE 2022<br/>
Registration Number : 032329-22<br>
Date:04/04/2026<br/>
Dataset Used:<strong> None</strong><br/>


## 1. Objectives
- Understand mathematical structures of Scalars,Vectors,Matrices and Tensors.
- Understand the use of Numpy and PyTorch libraries.
- Understand linear operations and their implementations using Numpy and PyTorch.
- Understand Numerical instability and Probability concepts that are used in machine learning.

## 2.Theoretical Background
### 2.1 Linear Algebra Concepts:
1. **Scalar** : Scalar is a single numerical value that conveys magnitude but no direction or dimension. It is a zero-dimensional entity that acts as a fundamental unit of computation. Scalars are 0 th ordered Tensors.
2. **Vector**: Vector is a single dimensional array that has both magnitude and direction or dimension. It is a 1st-order Tensor. Vectors represent features, weights or data points where each dimension reflects one characteristic or attribute.
3. **Matrices**: Matrices are rectangular arrays or two-dimensional grid consisting of numbers and are an example of 2nd-order tensors.A matrix is a two-dimensional grid or rectangular array of numbers arranged in rows and columns. THe rows and columns denote obseravtions and features resepectively. They are used to represent datasets, transformation functions and neural network weights.
4. **Tensors**: A tensor is a multi-dimensional generalization of scalars, vectors and matrices. It can represent data in three or more dimensions making it suitable for modeling highly complex relationships across multiple axes. In deep learning, tensors are used to store and process data such as images, videos or sequences where each dimension captures a specific feature or time-step.


| **Aspect** | **Scalar**| **Vector** | **Matrix** | **Tensor** |
| :--- | :--- | :--- | :--- | :--- |
| **Dimensionality** | 0D | 1D | 2D | ≥ 3D |
| **Representation** | Single numerical value | Ordered array of values | Two-dimensional grid of values | Multi-dimensional array of values |
| **Usage** | Represent basic quantities | Represent features or directions | Organize data in tabular form | Represent complex data structures |
| **Examples** | Error metric, probability | Feature vector, gradient | Data matrix, weight matrix | Image tensor, video tensor |



------

### 2.2 Probability Concepts:
1. Probability Distribution: A probability distribution is a mathematical function that describes the probability of different possible values of a variable. Probability distributions are often depicted using graphs or probability tables.<br>
Types of distributions:<br>
i. Uniform Distribution: All outcomes are equally likely.<br>
ii. Normal (Gaussian) Distribution: Symmetric, bell-shaped curve, defined by mean (μ) and standard deviation (σ).<br>
iii. Bernoulli Distribution: Models binary outcomes (e.g., coin flip).<br>

2. Entropy: In Machine Learning, entropy measures the level of disorder or uncertainty in a given dataset or system. It is a metric that quantifies the amount of information in a dataset, and it is commonly used to evaluate the quality of a model and its ability to make accurate predictions. In information theory,entropy quantifies uncertainty and variability in data. High entropy indicates high uncertainty in the system, while low entropy indicates low uncertainty.

3. Bayes' Theorem: Bayes' Theorem is a mathematical formula that determines conditional probability, which is the chance that something happens based on what has already happened in similar situations. It can help revise or update an existing prediction or theory given new evidence.

-------

### 2.3 Tensor Operations 
#### 2.3.1. Element Wise Operations:
- Addition and Subtraction: Performed on tensors of same shape where the corresponding elements can be added or subtracted.
- Hadamard Product: Element wise matrix multiplication that is different from normal matrix multiplication. Both the tenors need to be of same size.
- Activation Functions:  Performing a mathematical operation on every individual element within a tensor. Example : ReLU and Sigmoid functions.

#### 2.3.2. Linear Algebra Operations:
- Dot Product / Matrix Multiplication: The most common operation in neural networks, computed by multiplying matching elements and summing them, that is used to compute the output of a dense (fully connected) layer by multiplying input features by a weight matrix.
- Transpose: Swapping the axes of a tensor (e.g., flipping a matrix's rows and columns). Shuffling the dimensions of a tensor, such as changing a (3X4X5) tensor to (5X4X3) tensor by swapping axes.
- Tensor Contraction: A generalization of the dot product to higher dimensions, where products are summed over specific axes. This reduces the rank (order) of a tensor by summing over repeated indices.
- Eigen Vectors and Eigen Values : These represent invariant directions and scaling factors, respectively, where the tensor transforms a vector without changing its direction. Eigenvalues are scalars λ that satisfy the equation \(Av = λv\), where \(A\) is a square matrix and \(v\) is a non-zero vector (the eigenvector).Eigenvectors are vectors that, when multiplied by the matrix, result in a scaled version of themselves

#### 2.3.3. Shape Manipulations
- Reshaping: Altering the dimensions without altering the underlying data. Example: Convert a (3X4) tensor into (6X2) tensor , while retaining the total number of elements.
- Broadcasting: Automatically "stretching" a smaller tensor (like a scalar or vector) to match the shape of a larger tensor during an operation, allowing implicit element-wise operations between arrays of different shapes.
- Flattening: Converting a multi-dimensional tensor (like a 2D image) into a 1D vector, typically before entering a final classification layer. 

#### 2.3.4. Reduction Operations
- Sum/Mean: Calculating the average or total across a specific axis (e.g., averaging pixel values).
- Argmax: Finding the index of the maximum value, often used to determine the final predicted class in a classification model.
- Argmin: Finding the index of the minimum value.

## 3. DataSet Description

No dataset is used. All the numbers are generated within the notebook ,either hard-coded or generated using random functions, so **an external dataset is not required.**

## 4. Implementation

### 4.1 Setup

In [177]:
import numpy as np
import torch

#printing versions
print(f"Numpy version installed: {np.__version__}")
print(f"PyTorch version installed: {torch.__version__}")


Numpy version installed: 2.4.4
PyTorch version installed: 2.11.0


### 4.2 Creating Tensors

In [178]:
#Creating tensors
print("\nCreating tensors...")
print("Everything in float data type for calculations and consistency.")
print("\n1. Scalar:")
scalar_np = np.array(66.3).astype(np.float32)
scalar_pt = torch.tensor(67.3).float()
print("NumPy Scalar:", scalar_np)
print("PyTorch Scalar:", scalar_pt)
print("Shape of NumPy Scalar:", scalar_np.shape)
print("Shape of PyTorch Scalar:", scalar_pt.shape)


print("-"*75)

print("\n2. Vector:")
vector_np = np.array([55, 33, 22]).astype(np.float32)
vector_pt = torch.tensor([56, 34, 23]).float()
print("NumPy Vector:", vector_np, "Shape:", vector_np.shape)
print("PyTorch Vector:", vector_pt, "Shape:", vector_pt.shape)

print("-"*75)
print("\n3. Matrix:")
matrix_np = np.array([[23, 11, 53], [42, 64, 33], [46, 93, 92]]).astype(np.float32)
matrix_pt = torch.tensor([[24, 12, 54], [43, 65, 34], [47, 94, 93]]).float()
print("NumPy Matrix:\n", matrix_np, "\nShape:", matrix_np.shape)
print("PyTorch Matrix:\n", matrix_pt, "\nShape:", matrix_pt.shape)


print("-"*75)
print("\n4. 3D Tensor:")
tensor_3d_np = np.array([[[12, 23], [32, 42]], [[35, 66], [72, 83]], [[97, 72], [19, 37]]]).astype(np.float32)
tensor_3d_pt = torch.tensor([[[19, 20], [39, 47]], [[53, 67], [74, 28]], [[93, 12], [61, 32]]]).float()
print("NumPy 3D Tensor:\n", tensor_3d_np, "\nShape:", tensor_3d_np.shape)
print("PyTorch 3D Tensor:\n", tensor_3d_pt, "\nShape:", tensor_3d_pt.shape)


Creating tensors...
Everything in float data type for calculations and consistency.

1. Scalar:
NumPy Scalar: 66.3
PyTorch Scalar: tensor(67.3000)
Shape of NumPy Scalar: ()
Shape of PyTorch Scalar: torch.Size([])
---------------------------------------------------------------------------

2. Vector:
NumPy Vector: [55. 33. 22.] Shape: (3,)
PyTorch Vector: tensor([56., 34., 23.]) Shape: torch.Size([3])
---------------------------------------------------------------------------

3. Matrix:
NumPy Matrix:
 [[23. 11. 53.]
 [42. 64. 33.]
 [46. 93. 92.]] 
Shape: (3, 3)
PyTorch Matrix:
 tensor([[24., 12., 54.],
        [43., 65., 34.],
        [47., 94., 93.]]) 
Shape: torch.Size([3, 3])
---------------------------------------------------------------------------

4. 3D Tensor:
NumPy 3D Tensor:
 [[[12. 23.]
  [32. 42.]]

 [[35. 66.]
  [72. 83.]]

 [[97. 72.]
  [19. 37.]]] 
Shape: (3, 2, 2)
PyTorch 3D Tensor:
 tensor([[[19., 20.],
         [39., 47.]],

        [[53., 67.],
         [74., 28.]],

### 4.3 Element Wise Operations

In [179]:
A_np = np.random.rand(4, 4).astype(np.float32) * 100 
#for better visulation, using bigger values is easy.
B_np = np.random.rand(4, 4).astype(np.float32) * 100

print("\nRandomly generated 4x4 matrices A and B:")
print("A:\n", A_np)
print("B:\n", B_np)

print("-"*75)
#Using Numpy 
add_np = A_np + B_np
sub_np = A_np - B_np
mul_np = A_np * B_np
print("\nNumPy Operations:")
print("Addition:\n", add_np)
print("Subtraction:\n", sub_np)
print("Hadamard Product:\n", mul_np)

print("-"*75)

#Using PyTorch
A_pt = torch.tensor(A_np).float()
B_pt = torch.tensor(B_np).float()
add_pt = A_pt + B_pt
sub_pt = A_pt - B_pt
mul_pt = A_pt * B_pt
print("\nPyTorch Operations:")
print("Addition:\n", add_pt)
print("Subtraction:\n", sub_pt)
print("Hadamard Product:\n", mul_pt)

print("-"*75)


Randomly generated 4x4 matrices A and B:
A:
 [[97.229935  76.83856   11.195062  26.165262 ]
 [43.357075  46.32832   44.38793   65.748985 ]
 [32.056816   3.8901215 50.313824  20.680254 ]
 [93.68401   22.666794  23.668407  25.245077 ]]
B:
 [[18.988186 93.449844 99.2956   43.07411 ]
 [21.894985 37.909805 88.216064 12.151109]
 [80.64628  18.264078 64.49204  87.17194 ]
 [37.71859  37.253403 90.8348   74.8137  ]]
---------------------------------------------------------------------------

NumPy Operations:
Addition:
 [[116.218124 170.2884   110.49066   69.23937 ]
 [ 65.25206   84.23813  132.604     77.90009 ]
 [112.703094  22.1542   114.80586  107.852196]
 [131.4026    59.920197 114.503204 100.05878 ]]
Subtraction:
 [[ 78.241745 -16.611282 -88.10054  -16.908846]
 [ 21.46209    8.418514 -43.828133  53.597878]
 [-48.589462 -14.373957 -14.178219 -66.49169 ]
 [ 55.965424 -14.586609 -67.1664   -49.56862 ]]
Hadamard Product:
 [[1846.2201   7180.552    1111.6204   1127.0453  ]
 [ 949.3025   1756.2

Activation functions

In [180]:
#activation functions
#ReLU : max(0, x) , removes negative values
#Sigmoid : 1 / (1 + exp(-x)) , squashes values between 0 and 1
#tanh : (exp(x) - exp(-x)) / (exp(x) + exp(-x)) , squashes values between -1 and 1

#creating a random tensor for activation functions
random_tensor_np = np.random.randn(4, 4).astype(np.float32) * 10
random_tensor_pt = torch.tensor(random_tensor_np).float()

relu_np = np.maximum(0, random_tensor_np)
sigmoid_np = 1 / (1 + np.exp(-random_tensor_np))
tanh_np = (np.exp(random_tensor_np) - np.exp(-random_tensor_np)) / (np.exp(random_tensor_np) + np.exp(-random_tensor_np))

relu_pt = torch.relu(random_tensor_pt)
sigmoid_pt = torch.sigmoid(random_tensor_pt)
tanh_pt = torch.tanh(random_tensor_pt)

print("\nActivation Functions:")
print("Random Tensor:\n", random_tensor_np)
print("ReLU (NumPy):\n", relu_np)
print("Sigmoid (NumPy):\n", sigmoid_np)
print("Tanh (NumPy):\n", tanh_np)

print("-"*75)
print("Using PyTorch:\n", random_tensor_pt)
print("ReLU (PyTorch):\n", relu_pt)
print("Sigmoid (PyTorch):\n", sigmoid_pt)
print("Tanh (PyTorch):\n", tanh_pt)


Activation Functions:
Random Tensor:
 [[  8.001088    1.823541    6.1222267   6.508799 ]
 [-10.171966    8.840097  -14.090523   29.11247  ]
 [ 14.299053    1.4323605   6.301654    4.641523 ]
 [-13.412651  -12.168425  -17.747902    2.137855 ]]
ReLU (NumPy):
 [[ 8.001088   1.823541   6.1222267  6.508799 ]
 [ 0.         8.840097   0.        29.11247  ]
 [14.299053   1.4323605  6.301654   4.641523 ]
 [ 0.         0.         0.         2.137855 ]]
Sigmoid (NumPy):
 [[9.9966502e-01 8.6099046e-01 9.9781126e-01 9.9851197e-01]
 [3.8225648e-05 9.9985516e-01 7.5956228e-07 1.0000000e+00]
 [9.9999940e-01 8.0726880e-01 9.9817002e-01 9.9044913e-01]
 [1.4960945e-06 5.1918014e-06 1.9596754e-08 8.9452839e-01]]
Tanh (NumPy):
 [[ 0.9999998   0.94919026  0.99999034  0.99999565]
 [-1.          1.         -1.          1.        ]
 [ 1.          0.8921493   0.99999326  0.99981403]
 [-1.         -1.         -1.          0.97257686]]
---------------------------------------------------------------------------
U

### 4.4 Linear Algebra Operations

In [181]:
#Dot product
#Matrix Dot Product: A @ B or np.dot(A, B) or torch.matmul(A, B)
#Transpose: A.T or A.transpose() or A.t() in PyTorch
#Contraction: sum over specific axes, e.g., np.tensordot(A, B, axes=1) or torch.tensordot(A, B, dims=1)
#Eigenvalues and eigenvectors: np.linalg.eig(A) or torch.linalg.eig(A)

#using initial values of A and B for operations
#Dot product
dot_np = np.dot(A_np, B_np)
dot_pt = torch.matmul(A_pt, B_pt)

#Transpose
transpose_np = A_np.T
transpose_pt = A_pt.t()

#Contraction
contraction_np = np.tensordot(A_np, B_np, axes=1)
contraction_pt = torch.tensordot(A_pt, B_pt, dims=1)

#Eigenvalues and eigenvectors
eigenvalues_np, eigenvectors_np = np.linalg.eig(A_np)
eigenvalues_pt, eigenvectors_pt = torch.linalg.eig(A_pt)

print("\nLinear Algebra Operations:")
print("Dot Product (NumPy):\n", dot_np)
print("Dot Product (PyTorch):\n", dot_pt)
print("-"*75)
print("Original Matrix A :\n", A_np)
print("Transpose (NumPy):\n", transpose_np)
print("Transpose (PyTorch):\n", transpose_pt)
print("-"*75)
print("Contraction (NumPy):\n", contraction_np)
print("Contraction (PyTorch):\n", contraction_pt)
print("-"*75)
print("Eigenvalues (NumPy):\n", eigenvalues_np)
print("Eigenvalues (PyTorch):\n", eigenvalues_pt)
print("-"*75)
print("Eigenvectors (NumPy):\n", eigenvectors_np)
print("Eigenvectors (PyTorch):\n", eigenvectors_pt)


Linear Algebra Operations:
Dot Product (NumPy):
 [[ 5418.3564 13178.27   19531.61    8055.182 ]
 [ 7897.3105  9068.087  17227.033  11218.814 ]
 [ 5531.5273  4832.5234  8649.6     7361.2085]
 [ 5136.156  10986.797  15121.541   8262.681 ]]
Dot Product (PyTorch):
 tensor([[ 5418.3564, 13178.2695, 19531.6094,  8055.1821],
        [ 7897.3105,  9068.0869, 17227.0332, 11218.8145],
        [ 5531.5273,  4832.5234,  8649.5996,  7361.2085],
        [ 5136.1558, 10986.7969, 15121.5410,  8262.6807]])
---------------------------------------------------------------------------
Original Matrix A :
 [[97.229935  76.83856   11.195062  26.165262 ]
 [43.357075  46.32832   44.38793   65.748985 ]
 [32.056816   3.8901215 50.313824  20.680254 ]
 [93.68401   22.666794  23.668407  25.245077 ]]
Transpose (NumPy):
 [[97.229935  43.357075  32.056816  93.68401  ]
 [76.83856   46.32832    3.8901215 22.666794 ]
 [11.195062  44.38793   50.313824  23.668407 ]
 [26.165262  65.748985  20.680254  25.245077 ]]
Transpose

Eigenvlaues and Eigenvectors

In [182]:
#using a symmetric matrix for eigenvalues and eigenvectors to ensure real values
symmetric_matrix_np = np.array([[4, 2,5], [2, 3,8], [5, 8, 6]]).astype(np.float32)
symmetric_matrix_pt = torch.tensor(symmetric_matrix_np).float()

eigenvalues_sym_np, eigenvectors_sym_np = np.linalg.eig(symmetric_matrix_np)
eigenvalues_sym_pt, eigenvectors_sym_pt = torch.linalg.eig(symmetric_matrix_pt)
print("\nSymmetric Matrix:\n", symmetric_matrix_np)
print("Eigenvalues (NumPy):\n", eigenvalues_sym_np)
print("Eigenvalues (PyTorch):\n", eigenvalues_sym_pt)
print("-"*75)
print("Eigenvectors (NumPy):\n", eigenvectors_sym_np)
print("Eigenvectors (PyTorch):\n", eigenvectors_sym_pt)



Symmetric Matrix:
 [[4. 2. 5.]
 [2. 3. 8.]
 [5. 8. 6.]]
Eigenvalues (NumPy):
 [15.048474   2.012644  -4.0611186]
Eigenvalues (PyTorch):
 tensor([15.0485+0.j,  2.0126+0.j, -4.0611+0.j])
---------------------------------------------------------------------------
Eigenvectors (NumPy):
 [[ 0.4251177   0.8709746  -0.24632953]
 [ 0.54859775 -0.46439877 -0.6952512 ]
 [ 0.7199413  -0.16042778  0.6752388 ]]
Eigenvectors (PyTorch):
 tensor([[ 0.4251+0.j,  0.8710+0.j, -0.2463+0.j],
        [ 0.5486+0.j, -0.4644+0.j, -0.6953+0.j],
        [ 0.7199+0.j, -0.1604+0.j,  0.6752+0.j]])


### 4.5 Shape Manipulations

In [183]:
#Reshaping , broadcasting and flattenting

A_reshaped_np = A_np.reshape(2, 8)
A_reshaped_pt = A_pt.reshape(2, 8)
print("\nReshaping (4,4) to (2,8):")
print("Original shape of A:", A_np.shape)
print("Reshaped A (NumPy):\n", A_reshaped_np, "Shape:", A_reshaped_np.shape)
print("Reshaped A (PyTorch):\n", A_reshaped_pt, "Shape:", A_reshaped_pt.shape)
print("-"*75)

#Broadcasting
#Adding a vector to a matrix
vector_broadcast_np = np.array([23, 21, 32, 45]).astype(np.float32)
vector_broadcast_pt = torch.tensor(vector_broadcast_np).float()
broadcast_add_np = A_np + vector_broadcast_np
broadcast_add_pt = A_pt + vector_broadcast_pt
print("\nBroadcasting - Adding a vector to a matrix:")
print("Matrix A:\n", A_np)
print("Vector:\n", vector_broadcast_np)
print("Result of A + Vector (NumPy):\n", broadcast_add_np)
print("Result of A + Vector (PyTorch):\n", broadcast_add_pt)
print("-"*75)

#Flattening
A_flattened_np = A_np.flatten()
A_flattened_pt = A_pt.flatten()
print("\nFlattening:")
print("Original shape of A:", A_np.shape)
print("Flattened A (NumPy):\n", A_flattened_np, "Shape:", A_flattened_np.shape)
print("Flattened A (PyTorch):\n", A_flattened_pt, "Shape:", A_flattened_pt.shape)
print("-"*75)



Reshaping (4,4) to (2,8):
Original shape of A: (4, 4)
Reshaped A (NumPy):
 [[97.229935  76.83856   11.195062  26.165262  43.357075  46.32832
  44.38793   65.748985 ]
 [32.056816   3.8901215 50.313824  20.680254  93.68401   22.666794
  23.668407  25.245077 ]] Shape: (2, 8)
Reshaped A (PyTorch):
 tensor([[97.2299, 76.8386, 11.1951, 26.1653, 43.3571, 46.3283, 44.3879, 65.7490],
        [32.0568,  3.8901, 50.3138, 20.6803, 93.6840, 22.6668, 23.6684, 25.2451]]) Shape: torch.Size([2, 8])
---------------------------------------------------------------------------

Broadcasting - Adding a vector to a matrix:
Matrix A:
 [[97.229935  76.83856   11.195062  26.165262 ]
 [43.357075  46.32832   44.38793   65.748985 ]
 [32.056816   3.8901215 50.313824  20.680254 ]
 [93.68401   22.666794  23.668407  25.245077 ]]
Vector:
 [23. 21. 32. 45.]
Result of A + Vector (NumPy):
 [[120.229935  97.83856   43.19506   71.16526 ]
 [ 66.35707   67.32832   76.38793  110.748985]
 [ 55.056816  24.890121  82.31383   65.

### 4.6 Reduction Operations

In [184]:
#Sum, Mean, argmax, argmin
sum_np = np.sum(A_np)
mean_np = np.mean(A_np)
argmax_np = np.argmax(A_np)
argmin_np = np.argmin(A_np)
#using the same values of A for PyTorch
sum_pt = torch.sum(A_pt)
mean_pt = torch.mean(A_pt)
argmax_pt = torch.argmax(A_pt)
argmin_pt = torch.argmin(A_pt)
print("\nSum, Mean, Argmax, Argmin:")
print("Matrix A:\n", A_np)
print("Sum (NumPy):", sum_np)
print("Sum (PyTorch):", sum_pt.item())
print("-"*75)
print("Mean (NumPy):", mean_np)
print("Mean (PyTorch):", mean_pt.item())
print("-"*75)
print("Argmax (NumPy):", argmax_np, "Value:", A_np.flatten()[argmax_np])
print("Argmax (PyTorch):", argmax_pt.item(), "Value:", A_pt.flatten()[argmax_pt].item())
print("-"*75)
print("Argmin (NumPy):", argmin_np, "Value:", A_np.flatten()[argmin_np])
print("Argmin (PyTorch):", argmin_pt.item(), "Value:", A_pt.flatten()[argmin_pt].item())



Sum, Mean, Argmax, Argmin:
Matrix A:
 [[97.229935  76.83856   11.195062  26.165262 ]
 [43.357075  46.32832   44.38793   65.748985 ]
 [32.056816   3.8901215 50.313824  20.680254 ]
 [93.68401   22.666794  23.668407  25.245077 ]]
Sum (NumPy): 683.4564
Sum (PyTorch): 683.4564208984375
---------------------------------------------------------------------------
Mean (NumPy): 42.716026
Mean (PyTorch): 42.716026306152344
---------------------------------------------------------------------------
Argmax (NumPy): 0 Value: 97.229935
Argmax (PyTorch): 0 Value: 97.22993469238281
---------------------------------------------------------------------------
Argmin (NumPy): 9 Value: 3.8901215
Argmin (PyTorch): 9 Value: 3.8901214599609375


### 4.7 Additional Operations (Norms,Entropy, Softmax)

In [185]:
#Norms, entropy, softmax

# NumPy: Maximum absolute column sum
l1_np = np.linalg.norm(A_np, ord=1)

# PyTorch: Maximum absolute column sum
l1_pt = torch.max(torch.sum(torch.abs(A_pt), dim=0)).item()

# NumPy: Maximum singular value
l2_np = np.linalg.norm(A_np, ord=2)

# PyTorch: Maximum singular value (use SVD)
l2_pt = torch.linalg.svdvals(A_pt)[0].item()

# NumPy: Maximum absolute row sum
inf_np = np.linalg.norm(A_np, ord=np.inf)

# PyTorch: Maximum absolute row sum
inf_pt = torch.max(torch.sum(torch.abs(A_pt), dim=1)).item()
print("\nNorms:")
print("Matrix A:\n", A_np)
print("L1 Norm (NumPy):", l1_np)
print("L1 Norm (PyTorch):", l1_pt)
print("-"*75)
print("L2 Norm (NumPy):", l2_np)
print("L2 Norm (PyTorch):", l2_pt)
print("-"*75)
print("Infinity Norm (NumPy):", inf_np)
print("Infinity Norm (PyTorch):", inf_pt)
print("-"*75)

# Softmax (with numerical stability fix)
A_np_stable = A_np - np.max(A_np, axis=0)  # Subtract max for stability
A_pt_stable = A_pt - torch.max(A_pt, dim=0).values  # Subtract max for stability

softmax_np = np.exp(A_np_stable) / np.sum(np.exp(A_np_stable), axis=0)
softmax_pt = torch.softmax(A_pt_stable, dim=0)

print("\nSoftmax:")
print("Matrix A (Stable):\n", A_np_stable)
print("Softmax (NumPy):\n", softmax_np)
print("Softmax (PyTorch):\n", softmax_pt)
print("-"*75)

# Entropy (with numerical stability fix)
entropy_np = -np.sum(softmax_np * np.log(softmax_np + 1e-10))
entropy_pt = -torch.sum(softmax_pt * torch.log(softmax_pt + 1e-10)).item()

print("Entropy of Softmax Output:")
print("Entropy (NumPy):", entropy_np)
print("Entropy (PyTorch):", entropy_pt)


Norms:
Matrix A:
 [[97.229935  76.83856   11.195062  26.165262 ]
 [43.357075  46.32832   44.38793   65.748985 ]
 [32.056816   3.8901215 50.313824  20.680254 ]
 [93.68401   22.666794  23.668407  25.245077 ]]
L1 Norm (NumPy): 266.32785
L1 Norm (PyTorch): 266.3278503417969
---------------------------------------------------------------------------
L2 Norm (NumPy): 186.68054
L2 Norm (PyTorch): 186.68052673339844
---------------------------------------------------------------------------
Infinity Norm (NumPy): 211.42883
Infinity Norm (PyTorch): 211.4288330078125
---------------------------------------------------------------------------

Softmax:
Matrix A (Stable):
 [[  0.          0.        -39.118763  -39.583725 ]
 [-53.87286   -30.510242   -5.925892    0.       ]
 [-65.17312   -72.94844     0.        -45.068733 ]
 [ -3.5459213 -54.17177   -26.645416  -40.503906 ]]
Softmax (NumPy):
 [[9.7196645e-01 1.0000000e+00 1.0227731e-17 6.4417914e-18]
 [3.8991099e-24 5.6178488e-14 2.6623190e-03 1.0

## 5. Experiments

### 5.1 Numerical Instability in Tensor Operations

In [186]:
#numerical instability demonstration
print("\nNumerical Instability Demonstration:")
large_values_np = np.array([1000, 1001, 1002]).astype(np.float32)
large_values_pt= torch.tensor(large_values_np).float()
softmax_large_np = np.exp(large_values_np) / np.sum(np.exp(large_values_np))
softmax_large_pt = torch.softmax(large_values_pt, dim=0)
print("Large Values:\n", large_values_np)
print("Softmax (NumPy) without stability fix:\n", softmax_large_np)
print("Softmax (PyTorch) without stability fix:\n", softmax_large_pt)

#fixing numerical instability with softmax
print("\nFixing Numerical Instability with Softmax:")
large_stable_np = large_values_np - np.max(large_values_np) #gives [-2, -1, 0]
large_stable_pt = large_values_pt - torch.max(large_values_pt).item() #gives [-2, -1, 0]
softmax_large_stable_np = np.exp(large_stable_np) / np.sum(np.exp(large_stable_np))
softmax_large_stable_pt = torch.softmax(large_stable_pt, dim=0)
print("\nSoftmax with Numerical Stability Fix:")
print("Large Values (Stable):\n", large_stable_np)
print("Softmax (NumPy) with stability fix:\n", softmax_large_stable_np)
print("Softmax (PyTorch) with stability fix:\n", softmax_large_stable_pt)


Numerical Instability Demonstration:
Large Values:
 [1000. 1001. 1002.]
Softmax (NumPy) without stability fix:
 [nan nan nan]
Softmax (PyTorch) without stability fix:
 tensor([0.0900, 0.2447, 0.6652])

Fixing Numerical Instability with Softmax:

Softmax with Numerical Stability Fix:
Large Values (Stable):
 [-2. -1.  0.]
Softmax (NumPy) with stability fix:
 [0.09003057 0.24472848 0.66524094]
Softmax (PyTorch) with stability fix:
 tensor([0.0900, 0.2447, 0.6652])


/var/folders/hw/3b_tb3h96kj9v39y_mth3yc80000gn/T/ipykernel_6899/695665763.py:5: RuntimeWarning: overflow encountered in exp
  softmax_large_np = np.exp(large_values_np) / np.sum(np.exp(large_values_np))
/var/folders/hw/3b_tb3h96kj9v39y_mth3yc80000gn/T/ipykernel_6899/695665763.py:5: RuntimeWarning: invalid value encountered in divide
  softmax_large_np = np.exp(large_values_np) / np.sum(np.exp(large_values_np))


### 5.2 Precision Experiment (Float32 vs Float64)

In [187]:
#precision experiment, float32 vs float64
print("\nPrecision Experiment:")
C_float32_np = np.random.rand(4, 4).astype(np.float32) * 100
C_float64_np = C_float32_np.astype(np.float64)
C_float32_pt = torch.tensor(C_float32_np).float()
C_float64_pt = torch.tensor(C_float64_np).double()

#finding sum of all elements in C for both precisions
sum_float32_np = np.sum(C_float32_np)
sum_float64_np = np.sum(C_float64_np)
sum_float32_pt = torch.sum(C_float32_pt).item()
sum_float64_pt = torch.sum(C_float64_pt).item()
print("Sum of elements in C (float32, NumPy):", sum_float32_np)
print("Sum of elements in C (float64, NumPy):", sum_float64_np)
print("Sum of elements in C (float32, PyTorch):", sum_float32_pt)
print("Sum of elements in C (float64, PyTorch):", sum_float64_pt)

#result
print("\nPrecision Comparison:")
print("Difference in sums (NumPy):", abs(sum_float64_np - sum_float32_np))
print("Difference in sums (PyTorch):", abs(sum_float64_pt - sum_float32_pt))


Precision Experiment:
Sum of elements in C (float32, NumPy): 812.1607
Sum of elements in C (float64, NumPy): 812.1607015132904
Sum of elements in C (float32, PyTorch): 812.1607666015625
Sum of elements in C (float64, PyTorch): 812.1607015132904

Precision Comparison:
Difference in sums (NumPy): 4.0531158447265625e-06
Difference in sums (PyTorch): 6.508827209472656e-05


## 6. Results

### 6.1 Operations
<ul>
<li> Scalars, vectors, matrices, and 3D tensors were created in both NumPy and PyTorch using consistent data types (float32).</li>
<li>Element-wise operations (addition, subtraction, Hadamard product, ReLU, Sigmoid, Tanh) yielded identical results with both NumPy and PyTorch.</li>
<li>Linear algebra operations (matrix multiplication, transpose, tensor contraction, eigenvalues/eigenvectors) were consistent across both libraries with very identical results.</li>
<li>Data integraty and orderr were preserved as intended in shape manipulations (reshaping, broadcasting, flattening).</li>
<li>Reduction operations (sum, mean, argmax, argmin) also returned identical results in usage of both libraries.</li>
</ul>


### 6.2 Norms, Softmax, and Entropy
<ul>
<li>L1, L2, and Infinity norms matched between NumPy and PyTorch.</li>
<li>Softmax, with numerical stabilization, produced valid probability distributions.</li>
<li>Entropy of the softmax output was near-zero, indicating low uncertainty.</li>
</ul>


### 6.3 Experiments
<ul>
<li>Naive softmax caused overflow (NaN), whereas built-in softmax from PyTorch handled it correctly.</li>
<li>Overflow was fixed using Manual stabilization in NumPy which also matched the PyTorch’s results.</li>
<li>Float32 and Float64 precision differences were consistent with expected floating-point errors.</li>


## 7. Analysis & Discussion


### 7.1 Consistency and Purpose: NumPy vs PyTorch
- NumPy and PyTorch produced **identical numerical results** for all operations  with the (differences < 10⁻⁵), which proved that they share the same float32 arithmetic.
- The only difference was purpose, NumPy handles general computation, while PyTorch’s tensors include autograd for automatic differentiation, enabling gradient descent and training.
- For deep learning, PyTorch is essential because only it can compute gradients, and also has easy functions implementation compared to manual NumPy computations.

### 7.2 Numerical Considerations: Stability and Precision
- Numerical instability in softmax (overflow) can break training entirely without proper stabilization.
- PyTorch handles this internally, but manual implementations in NumPy must be applied with fixes to avoid NaN outputs.
- Float32 vs Float64: Float32’s precision gaps are small per operation but accumulate quickly in large-scale training, whereas float64 remains critical for precise scientific calculations.


### 7.3 ML Applications: Eigenvalues, Broadcasting, and Entropy
- Eigenvalues reveal matrix properties where negative values indicate invalid covariance matrices (common in PCA), while positive eigenvalues define valid principal components and their variance contributions.
- Broadcasting is powerful but risky as misaligned shapes can silently produce wrong results.
- Entropy starts high in untrained models (uncertainty) and drops to near-zero as training progresses. Monitoring entropy helps diagnose training issues such as sudden spikes often signal instability or bad batches.

## 8. Conclusion


- **Tensors**: Core data structure of deep learning as operations like reshaping and reduction form the backbone of neural networks.
- **NumPy vs PyTorch**: Numerically equivalent but PyTorch’s autograd engine makes it essential for training models and is easier to implement.
- **Numerical Stability**: Critical for training as simple fixes like max-shift prevent softmax overflow from breaking computations.
- **Float32**: Balances speed and memory efficiency for most tasks.
- **Entropy & Probability Theory**: Connect tensor operations to statistical learning goals.